// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trivista.LoanApp.ApplicationCore.Data.Context;

#nullable disable

namespace Trivista.LoanApp.ApplicationCore.Data.Migrations
{
    [DbContext(typeof(TrivistaDbContext))]
    [Migration("20230514122125_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trivista.LoanApp.ApplicationCore.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dob")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("LoaneeTypes")
                        .HasColumnType("int");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Trivista.LoanApp.ApplicationCore.Entities.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MaximumLoanAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MaximumTenure")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Loan");
                });

            modelBuilder.Entity("Trivista.LoanApp.ApplicationCore.Entities.LoanRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bvn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisbursedLoanStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("Interest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LoanApplicationStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("LoanRequest");
                });

            modelBuilder.Entity("Trivista.LoanApp.ApplicationCore.Entities.LoanRequest", b =>
                {
                    b.HasOne("Trivista.LoanApp.ApplicationCore.Entities.Customer", "Customer")
                        .WithMany("LoanRequests")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Trivista.LoanApp.ApplicationCore.Entities.CustomerRemitterInformation", "CustomerRemitterInformation", b1 =>
                        {
                            b1.Property<Guid>("LoanRequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AverageSixMonthsSalary")
                                .HasColumnType("decimal(18, 2)");

                            b1.Property<bool>("IsRemittaUser")
                                .HasColumnType("bit");

                            b1.Property<decimal>("OtherLoansCollected")
                                .HasColumnType("decimal(18, 2)");

                            b1.HasKey("LoanRequestId");

                            b1.ToTable("LoanRequest");

                            b1.WithOwner()
                                .HasForeignKey("LoanRequestId");
                        });

                    b.OwnsOne("Trivista.LoanApp.ApplicationCore.Entities.ValueObjects.LoanDetails", "LoanDetails", b1 =>
                        {
                            b1.Property<Guid>("LoanRequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("LoanAmount")
                                .HasColumnType("decimal(18, 2)");

                            b1.Property<decimal>("RepaymentScheduleType")
                                .HasColumnType("decimal(18, 2)");

                            b1.Property<string>("purpose")
                                .IsRequired()
                                .HasColumnType("nvarchar(400)");

                            b1.Property<int>("tenure")
                                .HasColumnType("int");

                            b1.HasKey("LoanRequestId");

                            b1.ToTable("LoanRequest");

                            b1.WithOwner()
                                .HasForeignKey("LoanRequestId");
                        });

                    b.OwnsOne("Trivista.LoanApp.ApplicationCore.Entities.ValueObjects.SalaryDetails", "SalaryDetails", b1 =>
                        {
                            b1.Property<Guid>("LoanRequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AccountName")
                                .IsRequired()
                                .HasColumnType("nvarchar(70)");

                            b1.Property<byte[]>("AccountStatementFile")
                                .IsRequired()
                                .HasColumnType("varbinary(max)");

                            b1.Property<long>("AccountStatementFileLength")
                                .HasColumnType("bigint");

                            b1.Property<string>("AccountStatementFileName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("AccountStatementFileType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("AverageMonthlyNetSalary")
                                .HasColumnType("decimal(18, 2)");

                            b1.Property<string>("BankName")
                                .IsRequired()
                                .HasColumnType("nvarchar(80)");

                            b1.Property<string>("SalaryAccountNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(12)");

                            b1.HasKey("LoanRequestId");

                            b1.ToTable("LoanRequest");

                            b1.WithOwner()
                                .HasForeignKey("LoanRequestId");
                        });

                    b.OwnsOne("Trivista.LoanApp.ApplicationCore.Entities.ValueObjects.kycDetails", "kycDetails", b1 =>
                        {
                            b1.Property<Guid>("LoanRequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CustomerAddress")
                                .IsRequired()
                                .HasColumnType("nvarchar(300)");

                            b1.Property<string>("CustomerCity")
                                .IsRequired()
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("CustomerCountry")
                                .IsRequired()
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("CustomerEmail")
                                .IsRequired()
                                .HasColumnType("nvarchar(300)");

                            b1.Property<string>("CustomerFirstName")
                                .IsRequired()
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("CustomerLastName")
                                .IsRequired()
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("CustomerMiddleName")
                                .IsRequired()
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("CustomerOccupation")
                                .IsRequired()
                                .HasColumnType("nvarchar(300)");

                            b1.Property<string>("CustomerPhoneNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(300)");

                            b1.Property<string>("CustomerPostalCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("CustomerState")
                                .IsRequired()
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("LoanRequestId");

                            b1.ToTable("LoanRequest");

                            b1.WithOwner()
                                .HasForeignKey("LoanRequestId");
                        });

                    b.Navigation("Customer");

                    b.Navigation("CustomerRemitterInformation")
                        .IsRequired();

                    b.Navigation("LoanDetails")
                        .IsRequired();

                    b.Navigation("SalaryDetails")
                        .IsRequired();

                    b.Navigation("kycDetails")
                        .IsRequired();
                });

            modelBuilder.Entity("Trivista.LoanApp.ApplicationCore.Entities.Customer", b =>
                {
                    b.Navigation("LoanRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
